# Generated by Django 2.1.7 on 2019-02-22 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190222_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='topic',
            name='top_name',
            field=models.CharField(default='SOME STRING', max_length=264, unique=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=264, unique=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(on_delete=None, to='first_app.Webpage'),
        ),
    ]
